# Generated by Django 4.1 on 2024-02-02 14:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Programming and electronics', 'Lập trình - Điện tử'), ('Mechanical and design', 'Cơ khí - Thiết kế'), ('Business', 'Quản lí - Tài chính'), ('Communication and Foreign Affairs', 'Truyền thông - Đối ngoại')], max_length=100)),
                ('desc', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
                ('pubdate', models.DateField()),
                ('updateDate', models.DateField()),
                ('editors', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('views', models.PositiveIntegerField()),
            ],
        ),
    ]
