# Generated by Django 4.1 on 2024-02-04 11:18

from django.db import migrations, models
import orr.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Programming and electronics', 'Lập trình - Điện tử'), ('Mechanical and design', 'Cơ khí - Thiết kế'), ('Business', 'Quản lí - Tài chính'), ('Communication and Foreign Affairs', 'Truyền thông - Đối ngoại')], max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(default=orr.models.default_img, null=True, upload_to='images/')),
                ('content', tinymce.models.HTMLField()),
                ('pubdate', models.DateField()),
                ('update_date', models.DateField(blank=True, null=True)),
                ('editors', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
