# Generated by Django 4.1 on 2024-02-02 14:57

from django.db import migrations, models
import orr.models


class Migration(migrations.Migration):

    dependencies = [
        ('orr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updateDate',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=orr.models.default_img, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='editors',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveBigIntegerField(),
        ),
    ]
