# Generated by Django 4.1 on 2024-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orr', '0002_remove_article_updatedate_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.AlterField(
            model_name='article',
            name='editors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
